on:
  workflow_dispatch:
  push:
    branches:
      - '*'
      - '*/*'

permissions:
  contents: read

jobs:
  build:
    name: Build installable packages
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

        ######## TEMPORARY ########
        ## util sdk got released ##
        ######## TEMPORARY ########
      - run: |
          composer config prefer-stable true
          composer config minimum-stability dev
        ######## TEMPORARY ########
        ########    END    ########
        ######## TEMPORARY ########

      - uses: actions/setup-go@v4

      - run: go install github.com/FriendsOfShopware/shopware-cli@latest

      - uses: actions/setup-node@v3
        with:
          node-version: '16'

      - run: shopware-cli extension zip . --disable-git --release

      - uses: actions/upload-artifact@v3
        with:
          name: Module bundles
          path: "*.zip"
